spring.application.name=UserManagement

spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=1Qy1Jn0SHzmG4rox58xhLh1wbfWf_LgvfyQO002b3T4